# Generated by Django 4.2.20 on 2025-04-02 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='certificado',
            table='certificado',
        ),
    ]
