# Generated by Django 4.2.20 on 2025-04-03 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_certificado_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Certificado',
            new_name='Treinamento',
        ),
        migrations.AlterModelTable(
            name='treinamento',
            table='treinamento',
        ),
    ]
