# Generated by Django 4.2.20 on 2025-04-03 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_certificado_treinamento_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='treinamento',
            old_name='validade_meses',
            new_name='validade',
        ),
    ]
