# Generated by Django 4.2.20 on 2025-04-07 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_atendimento_coordenador_gruporisco_grupofuncao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoTreinamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tipotreinamento',
            },
        ),
        migrations.CreateModel(
            name='GrupoTreinamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.grupo')),
                ('tipotreinamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.tipotreinamento')),
                ('treinamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.treinamento')),
            ],
            options={
                'db_table': 'grupotreinamento',
            },
        ),
    ]
